# the below command is to encrypt the dockerhub username and password
# echo -n '{"auths":{"https://hub.docker.com":{"username":"YOUR_USERNAME","password":"YOUR_PASSWORD","auth":"'"$(echo -n 'YOUR_USERNAME:YOUR_PASSWORD' | base64)"'"}}}' | base64 -w 0
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: three-tier
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >
    eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tIjp7InVzZXJuYW1lIjoidmluYXkyODA2IiwicGFzc3dvcmQiOiJBbmFuZEAxMjMiLCJhdXRoIjoiZG1sdVlYa3lPREEyT2tGdVlXNWtRREV5TXc9PSJ9fX0=
