apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: three-tier
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  JWT_SECRET: c2VjcmV0
