package com.atu.green_global_initiative_api.model.dao;

import jakarta.persistence.*;
import lombok.Data;
import org.springframework.context.annotation.Primary;

/**
 * Represents the "Contact Us" form submission in the database.
 * This entity is mapped to the "contact_us" table, where users can submit their queries.
 *
 * The fields in this class capture the details of the query including the user's name, email,
 * phone number, and the message they want to send.
 *
 * <p>Example usage:</p>
 * <pre>
 * ContactUs contact = new ContactUs();
 * contact.setName("John Doe");
 * contact.setEmail("john.doe@example.com");
 * contact.setPhone("123-456-7890");
 * contact.setMessage("I would like to know more about your services.");
 * </pre>
 *
 * <p>This entity is used in the persistence layer of the application to manage "Contact Us" form submissions.</p>
 *
 * @author John Kirubaharan Ravichandran
 * @since 2025-03-19
 */
@Entity
@Data
@Table(name="contact_us")
public class ContactUs {
    /**
     * Unique identifier for the contact query.
     * This is automatically generated by the database upon insertion.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="query_id", unique = true, nullable = false)
    private int queryId;

    /**
     * The name of the person submitting the query.
     * This field cannot be null.
     */
    @Column(name="name",nullable = false)
    private String name;

    /**
     * The email address of the person submitting the query.
     * This field cannot be null.
     */
    @Column(name="email", nullable = false)
    private String email;

    /**
     * The phone number of the person submitting the query.
     * This field cannot be null.
     */
    @Column(name="phone", nullable = false)
    private String phone;

    /**
     * The message or query submitted by the person.
     * This field cannot be null.
     */
    @Column(name="message", nullable = false)
    private String message;
}
