name: Run Selenium Tests on Staging Deployment

on:
  workflow_dispatch: # Trigger the workflow manually

jobs:
  run-selenium-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Install Maven Dependencies
      run: mvn clean install

    - name: Install Microsoft Edge Browser
      run: |
        choco install microsoft-edge --version 134.0.3124.93

    - name: Install Edge WebDriver
      run: |
        choco install microsoft-edge-webdriver --version 134.0.3124.93

    - name: Run Selenium Tests with TestNG
      run: |
        mvn test -Dsurefire.suiteXmlFiles=testng.xml

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-test-results
        path: target/surefire-reports/*

    - name: Notify on Failure (Optional)
      if: failure()
      uses: slackapi/slack-github-action@v1.23
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL }}
        slack-message: "Selenium TestNG tests failed in the staging environment. Please check the surefire reports."
        status: failure
