name: OWASP Dependency-Check

on:
  push:
    branches: [ NGGI-90-integrate-owasp-dependency-check-bot ]
  pull_request:
    branches: [ NGGI-90-integrate-owasp-dependency-check-bot ]

permissions:
  contents: read
  security-events: write

jobs:
  frontend-scan:
    name: Angular Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd green-global-initiative-ui
          npm install

      - name: Run OWASP Dependency-Check (Angular)
        run: |
          mkdir -p reports/green-global-initiative-ui
          docker run --rm \
            -v ${{ github.workspace }}/green-global-initiative-ui:/src \
            -v ${{ github.workspace }}/reports/green-global-initiative-ui:/report \
            owasp/dependency-check \
            --scan /src \
            --format ALL \
            --project Angular-Project \
            --out /report

      - name: Upload Angular Report
        uses: actions/upload-artifact@v4
        with:
          name: Angular-Dependency-Check-Report
          path: reports/green-global-initiative-ui

  backend-scan:
    name: Spring Boot Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and resolve dependencies
        run: |
          cd backend
          ./mvnw clean install -DskipTests

      - name: Run OWASP Dependency-Check (Spring Boot)
        run: |
          mkdir -p reports/backend
          docker run --rm \
            -v ${{ github.workspace }}/backend:/src \
            -v ${{ github.workspace }}/reports/backend:/report \
            owasp/dependency-check \
            --scan /src \
            --format ALL \
            --project Spring-Boot-Project \
            --out /report

      - name: Upload Spring Boot Report
        uses: actions/upload-artifact@v4
        with:
          name: Spring-Boot-Dependency-Check-Report
          path: reports/backend

      - name: Check for vulnerabilities
        run: |
          if grep -q '<severity>CRITICAL</severity>' reports/backend/dependency-check-report.xml; then
            echo "CRITICAL vulnerabilities found!" && exit 1;
          else
            echo "No critical vulnerabilities detected.";
          fi
