name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - NGGI-112-ci-yaml-file-integration-with-all-the-tools-frontend-ui
  pull_request:
    branches:
      - NGGI-112-ci-yaml-file-integration-with-all-the-tools-frontend-ui

jobs:
  build:
    runs-on: [self-hosted]
    permissions:
      contents: write

    env:
      COVERAGE_THRESHOLD: 75
      DOCKER_CLEANUP: true

    steps:
      # Cleanup previous runs
      - name: Remove folder if it exists
        run: |
          if [ -d "/home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/reports" ]; then
            sudo rm -rf /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/reports
            echo "Folder deleted."
          else
            echo "Folder does not exist. Skipping deletion."
          fi
        shell: bash

      - name: Create reports directory
        run: |
          mkdir -p /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/reports
          mkdir -p /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui/documentation
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ./green-global-initiative-ui/node_modules
          key: npm-${{ hashFiles('green-global-initiative-ui/package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install dependencies
        working-directory: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui
        run: |
          npm install
          npm install --save-dev @compodoc/compodoc @angular/cli

      - name: Build the project
        working-directory: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui
        run: npm run build

      - name: Run Tests in Headless Mode
        working-directory: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui
        run: |
          npm test -- --browsers=ChromeHeadless --watch=false --code-coverage --karma-config=karma.conf.js --reporters junit || true

      - name: Extract Coverage Percentage
        working-directory: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui
        run: |
          COVERAGE=$(node -pe "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "Coverage: $COVERAGE%"
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Fail if code coverage is below threshold
        run: |
          if [ -z "$COVERAGE" ]; then
            echo "Error: COVERAGE variable is not set."
            exit 1
          fi
          if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "Code coverage is below the threshold of $COVERAGE_THRESHOLD%"
            exit 1
          fi

      # Security scans
      - name: Run Snyk scan
        working-directory: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui
        run: |
          npm install -g snyk
          snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Clean Docker environment
        if: env.DOCKER_CLEANUP == 'true'
        run: |
          docker system prune -a -f --volumes
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Trivy File Scan
        working-directory: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui
        run: trivy fs . --severity HIGH,CRITICAL --ignore-unfixed > trivyfs-backend.txt

      - name: Build Docker image
        working-directory: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      - name: Trivy Image Scan (with retry)
        run: |
          if ! trivy image ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} --severity HIGH,CRITICAL > trivyimage-frontend.txt; then
            echo "First scan failed, cleaning and retrying..."
            docker system prune -a -f --volumes
            trivy image ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} --severity HIGH,CRITICAL > trivyimage-frontend.txt || true
          fi

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      # OWASP Dependency Check (corrected syntax)
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'green-global-initiative'
          path: '/home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui'
          format: 'ALL'
          out: '/home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/reports'
          args: '--failOnCVSS 7'

      # Documentation
      - name: Generate Compodoc documentation
        working-directory: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui
        run: |
          npx compodoc -p tsconfig.app.json -d documentation
        continue-on-error: true

      # Upload artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui/test-results

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui/coverage

      - name: Upload OWASP reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/reports/*

      - name: Upload Compodoc documentation
        uses: actions/upload-artifact@v4
        with:
          name: compodoc-documentation
          path: /home/ubuntu/actions-runner/frontend/green-global-initiative/green-global-initiative/green-global-initiative-ui/documentation/*