name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - NGGI-112-ci-yaml-file-integration-with-all-the-tools-frontend-ui
  pull_request:
    branches:
      - NGGI-112-ci-yaml-file-integration-with-all-the-tools-frontend-ui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug directory structure
      run: ls -la

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use Node.js 18.x (required for Angular CLI)

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: npm install --prefix green-global-initiative-ui

    - name: Build the project
      run: npm run build --prefix green-global-initiative-ui

    - name: Run Tests in Headless Mode
      run: npm test --prefix green-global-initiative-ui -- --browsers=ChromeHeadless --watch=false || true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME}}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: |
        cd green-global-initiative-ui
        docker build -t frontend_ui:latest .  # Replace with your preferred image name and tag

    - name: Set environment variables
      run: |
        echo "TRIVY_VERSION=latest" >> $GITHUB_ENV
        echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Cache Trivy DB
      id: cache-trivy-db
      uses: actions/cache@v4
      with:
        path: ~/.cache/trivy
        key: trivy-db-${{ runner.os }}-${{ runner.arch }}-${{ env.TRIVY_VERSION }}-${{ env.CACHE_DATE }}
        restore-keys: |
          trivy-db-${{ runner.os }}-${{ runner.arch }}-${{ env.TRIVY_VERSION }}-

    - name: Set up Trivy
      uses: aquasecurity/setup-trivy@v0.2.2
      with:
        trivy-version: '${{ env.TRIVY_VERSION }}'  # Explicit version instead of 'latest'

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'frontend_ui:latest'  # Use the image name you just built
        version: '${{ env.TRIVY_VERSION }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        args: --timeout 30m

    - name: Run Snyk security scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'green-global-initiative'  # Replace with your actual project name
        format: 'ALL'
        fail_on_cvss: 7

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: green-global-initiative-ui/test-results

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: green-global-initiative-ui/coverage

    - name: Fail if code coverage is below threshold
      run: |
        if [ "$(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc)" -eq 1 ]; then
          echo "Code coverage is below the threshold of $COVERAGE_THRESHOLD%"
          exit 1
        fi