name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - NGGI-112-ci-yaml-file-integration-with-all-the-tools-frontend-ui
  pull_request:
    branches:
      - NGGI-112-ci-yaml-file-integration-with-all-the-tools-frontend-ui

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List files in workspace
      run: |
        ls -R

    - name: Print working directory
      run: pwd

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd green-global-initiative-ui  # Correct path to the project
        npm install

    - name: Install Angular CLI locally
      run: |
        cd green-global-initiative-ui
        npm install @angular/cli --save-dev

    - name: Build the project
      run: |
        cd green-global-initiative-ui
        npm run build

    - name: Run Tests in Headless Mode
      run: |
        cd green-global-initiative-ui
        npm test -- --browsers=ChromeHeadless --watch=false || true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Trivy File Scan
      run: |
        cd green-global-initiative-ui
        trivy fs . --severity HIGH,CRITICAL --ignore-unfixed > trivyfs-backend.txt

    - name: Build Docker image
      run: |
        cd green-global-initiative-ui
        docker build -t ${DOCKER_HUB_USERNAME}/frontend:${GITHUB_SHA} .

    - name: Trivy Image Scan
      run: |
        trivy image ${DOCKER_HUB_USERNAME}/frontend:${GITHUB_SHA} --severity HIGH,CRITICAL > trivyimage-backend.txt

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'green-global-initiative'
        format: 'ALL'
        fail_on_cvss: 7

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: green-global-initiative-ui/test-results

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: green-global-initiative-ui/coverage

    - name: Fail if code coverage is below threshold
      run: |
        if [ "$(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc)" -eq 1 ]; then
          echo "Code coverage is below the threshold of $COVERAGE_THRESHOLD%"
          exit 1
        fi