name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - NGGI-112-ci-yaml-file-integration-with-all-the-tools-frontend-ui
  pull_request:
    branches:
      - NGGI-112-ci-yaml-file-integration-with-all-the-tools-frontend-ui

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      COVERAGE_THRESHOLD: 75  # Set your desired coverage threshold here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ./green-global-initiative-ui/node_modules
          key: npm-${{ hashFiles('green-global-initiative-ui/package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install dependencies
        working-directory: ./green-global-initiative-ui
        run: npm install

      - name: Install Angular CLI locally
        working-directory: ./green-global-initiative-ui
        run: npm install @angular/cli --save-dev

      - name: Build the project
        working-directory: ./green-global-initiative-ui
        run: npm run build

      - name: Run Tests in Headless Mode
        working-directory: ./green-global-initiative-ui
        run: |
          npm test -- --browsers=ChromeHeadless --watch=false --code-coverage --karma-config=karma.conf.js --reporters junit || true

      - name: Extract Coverage Percentage
        id: coverage
        working-directory: ./green-global-initiative-ui
        run: |
          # Run tests and capture the output
          TEST_OUTPUT=$(npm test -- --browsers=ChromeHeadless --watch=false --code-coverage --karma-config=karma.conf.js --reporters junit || true)
          
          # Extract the Lines coverage percentage from the output
          COVERAGE=$(echo "$TEST_OUTPUT" | grep -Eo 'Lines\s*:\s*[0-9.]+%' | awk '{print $3}' | sed 's/%//')
          
          if [ -z "$COVERAGE" ]; then
            echo "Error: Could not extract coverage percentage."
            exit 1
          else
            echo "Extracted coverage: $COVERAGE%"
            echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          fi

      - name: Fail if code coverage is below threshold
        run: |
          if [ -z "$COVERAGE" ]; then
            echo "Error: COVERAGE variable is not set."
            exit 1
          fi
          if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "Code coverage is below the threshold of $COVERAGE_THRESHOLD%"
            exit 1
          else
            echo "Code coverage is $COVERAGE%, which meets the threshold of $COVERAGE_THRESHOLD%"
          fi

      # Snyk Integration
      - name: Run Snyk to check for vulnerabilities
        working-directory: ./green-global-initiative-ui
        run: |
          npm install -g snyk
          snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install Trivy
        run: |
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Trivy File Scan
        working-directory: ./green-global-initiative-ui
        run: trivy fs . --severity HIGH,CRITICAL --ignore-unfixed > trivyfs-frontend.txt

      - name: Build Docker image
        working-directory: ./green-global-initiative-ui
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      - name: Trivy Image Scan
        run: trivy image ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} --severity HIGH,CRITICAL > trivyimage-frontend.txt

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      # OWASP Dependency Check with report generation
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'green-global-initiative'
          scan-path: './green-global-initiative-ui'
          format: 'ALL'
          output: './reports'
          fail_on_cvss: 7

      # Documentation
      - name: Generate Compodoc documentation
        working-directory: ./green-global-initiative-ui
        run: |
          npx compodoc -p tsconfig.app.json -d documentation
        continue-on-error: true

      # Upload all reports
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./green-global-initiative-ui/test-results

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./green-global-initiative-ui/coverage

      - name: Upload OWASP Dependency Check reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: ./reports/*

      - name: Upload Compodoc documentation
        uses: actions/upload-artifact@v4
        with:
          name: compodoc-documentation
          path: ./green-global-initiative-ui/documentation/*

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: |
            ./green-global-initiative-ui/trivyfs-frontend.txt
            ./trivyimage-frontend.txt